### PR TITLE
Outputs implementation

### PR DESCRIPTION
**Pull request by mlc-mlapis**
The initial design of the solution of how to pass inner outputs on a dynamic component instance to the outer web component.

### CODE REVIEW

**Comment by mlc-mlapis** [comment]
@brunob15 Did you look at the PR? Do you have any comments?

**Comment by brunob15** [comment]
Hi @mlc-mlapis, I'll make some time today to look at it. 

Thanks!

**Comment by mlc-mlapis** [comment]
@brunob15 Any news?

**Review by brunob15 — APPROVED** [review]

**Comment by brunob15** [comment]
Could you provide steps to test please @mlc-mlapis ?
I added an output to the TalkComponent in `ngx-element-app` project and I'm not able to catch the event with addEventListener.

Thanks.

**Comment by mlc-mlapis** [comment]
[**@brunob15**](https://github.com/brunob15) Sure, I can add it. It was just the first step to confirm the logic. I tried it inside our app, where it works fine, not in the original repo. Adding the test is necessary, and it also shows where you have the problem probably.

**Comment by brunob15** [comment]
Thank you @mlc-mlapis! I will wait for those testing steps so I can test it before publishing a new version of the library to npm.

**Comment by brunob15** [comment]
@mlc-mlapis any updates?

**Comment by mlc-mlapis** [comment]
**@brunob15** I apologize for the delay and hope to be ready at the beginning of the next week.

**Comment by johnmcase** [comment]
@mlc-mlapis @brunob15 Any updates on this?  Any idea when this update might be published to npm?

**Comment by mlc-mlapis** [comment]
@johnmcase I would also like to finish it. I am still waiting for any reaction from @brunob15. I am seriously thinking about re-creating the whole package from the ground.

**Comment by mlc-mlapis** [comment]
https://github.com/brunob15/ngx-element/pull/30

**Comment by brunob15** [comment]
Version 0.0.7 has been released to npm including this feature @mlc-mlapis @johnmcase

**Pull request merged**
